#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=20:50:00
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 2"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"



${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e15.out
sed -i -e "s/ecutwfc = 15/ecutwfc = 18/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e18.out
sed -i -e "s/ecutwfc = 18/ecutwfc = 20/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e20.out
sed -i -e "s/ecutwfc = 20/ecutwfc = 25/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e25.out
sed -i -e "s/ecutwfc = 25/ecutwfc = 30/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e30.out
sed -i -e "s/ecutwfc = 30/ecutwfc = 35/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e35.out
sed -i -e "s/ecutwfc = 35/ecutwfc = 40/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e40.out
sed -i -e "s/ecutwfc = 40/ecutwfc = 45/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e45.out
sed -i -e "s/ecutwfc = 45/ecutwfc = 50/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e50.out
sed -i -e "s/ecutwfc = 50/ecutwfc = 55/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e55.out


echo "--"
