#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=50:50:00
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 2"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"



${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e75.out
sed -i -e "s/ecutwfc = 75/ecutwfc = 80/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e80.out
sed -i -e "s/ecutwfc = 80/ecutwfc = 85/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e85.out
sed -i -e "s/ecutwfc = 85/ecutwfc = 90/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e90.out
sed -i -e "s/ecutwfc = 90/ecutwfc = 95/g" Conv_acell-ecut.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-ecut.in > Conv_acell-e95.out



echo "--"
