#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=00:00:10
#SBATCH --mail-user=pierre-paul.debreuck@student.uclouvain.be
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 1"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"

${QE} < input.in > output

echo "--"
