#!/usr/bin/expect -f

spawn ssh -X tuto09@gwcism.cism.ucl.ac.be
expect "password:"
send "xeXsESev\r"
expect "$ "
send "ssh -X tuto09@manneback.cism.ucl.ac.be\r"
expect "password:"
send "xeXsESev\r"
interact
