#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=20:30:00
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 2"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"


${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k01.out
sed -i -e "s/1 1 1/2 2 2/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k02.out
sed -i -e "s/2 2 2/3 3 3/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k03.out
sed -i -e "s/3 3 3/4 4 4/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k04.out
sed -i -e "s/4 4 4/6 6 6/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k06.out
sed -i -e "s/6 6 6/ 8 8 8/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k08.out
sed -i -e "s/8 8 8/10 10 10/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k10.out
sed -i -e "s/10 10 10/12 12 12/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k12.out
sed -i -e "s/12 12 12/14 14 14/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k14.out
sed -i -e "s/14 14 14/16 16 16/g" Conv_etot-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k16.out
sed -i -e "s/16 16 16/18 18 18/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k18.out
sed -i -e "s/18 18 18/20 20 20/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k20.out
sed -i -e "s/20 20 20/22 22 22/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k22.out
sed -i -e "s/22 22 22/24 24 24/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k24.out
sed -i -e "s/24 24 24/26 26 26/g" Conv_etot-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_etot-kp.in > Conv_etot-k26.out

echo "--"
