#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=01:30:00
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 2"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"



${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k02.out
sed -i -e "s/2 2 2/4 4 4/g" Conv_acell-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k04.out
sed -i -e "s/4 4 4/6 6 6/g" Conv_acell-kp.in
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k06.out

echo "--"
