#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=50:30:00
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 2"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"



${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k18.out
sed -i -e "s/18 18 18/20 20 20/g" Conv_acell-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k20.out
sed -i -e "s/20 20 20/22 22 22/g" Conv_acell-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k22.out
sed -i -e "s/22 22 22/24 24 24/g" Conv_acell-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k24.out
sed -i -e "s/24 24 24/26 26 26/g" Conv_acell-kp.in 
${MPI} ${MPIOPT} ${QE} -inp Conv_acell-kp.in > Conv_acell-k26.out

echo "--"
