#!/bin/bash
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --job-name=ph
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=96:00:00

#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT1="-np 4"
MPIOPT2="-np 32"
QEE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"
QEP="/home/ucl/naps/gbrunin/q-e/bin/ph.x"

${MPI} ${MPIOPT1} ${QEE} < scf.in > scf.out
${MPI} ${MPIOPT2} ${QEP} < ph.in > ph.out

echo "--"
