#!/bin/bash
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=1
#SBATCH --job-name=scf
#SBATCH --mem-per-cpu=4000M
#SBATCH --time=2:30:00
#SBATCH --mail-user=
#SBATCH --mail-type=ALL
#SBATCH --partition=Def

module purge
source /home/ucl/naps/gbrunin/SetEnv.sh intel13_intel

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK

MPI="mpirun"
MPIOPT="-np 2"
QE="/home/ucl/naps/gbrunin/q-e/bin/pw.x"


${MPI} ${MPIOPT} ${QE} -inp scfield.in > scfield.out
${MPI} ${MPIOPT} ${QE} -inp el-bands.in > el-bands.out

${MPI} ${MPIOPT} ${QE} -inp scfield80.in > scfield80.out
${MPI} ${MPIOPT} ${QE} -inp el-bands.in > el-bands80.out
${MPI} ${MPIOPT} ${QE} -inp scfield85.in > scfield85.out
${MPI} ${MPIOPT} ${QE} -inp el-bands.in > el-bands85.out

${MPI} ${MPIOPT} ${QE} -inp scfieldk6.in > scfieldk6.out
${MPI} ${MPIOPT} ${QE} -inp el-bands.in > el-bandsk6.out
${MPI} ${MPIOPT} ${QE} -inp scfieldk8.in > scfieldk8.out
${MPI} ${MPIOPT} ${QE} -inp el-bands.in > el-bandsk8.out


echo "--"
